server:
  port: ${PORT:8080}  # Default port 8080 if no PORT environment variable is set

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudprojdb  # Update with your MySQL database name
    username: newuser  # Update with your MySQL username
    password: newpassword  # Update with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update  # Set to 'update' to avoid data loss when restarting the application
  application:
    name: Manga CRUD

api:
  info:
    title: Manga API
    version: 1.0.0
    description: Manga API is a web service that provides online information about mangas.
  contact:
    email: mario-dacosta@hotmail.fr
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  uri:
    paths:
      mangas: /api/v1/mangas
